### PR TITLE
Make remaining time tick in real-time (dev)

### PR DESCRIPTION
**Pull request by Taewan-P**
- [x] Make sure the time ticks

- [x] Make sure when the time hits zero, it should move on to the next bus schedule

- [ ] When bus is not available for today, it should show up the tomorrow's first bus departure time

- [ ] No Bugs ( 😄)

**Let's merge this branch when all the items above are checked...!!**

### CODE REVIEW

**Comment by CXZ7720** [comment]
Looks awesome. I'm very looking forward to finishing your works. 🚀 🏆

**Comment by Taewan-P** [comment]
Bug fixed. Now we have to make the timer show tomorrow's schedule when no bus is available for today.

**Comment by Taewan-P** [comment]
I am not sure if this code has bugs. But all the features has been implemented. We still need to check for bugs.

**Comment by Taewan-P** [comment]
~~One issue added~~

~~- [ ] When the page is not reloaded for a long time and it is the time of the day when no bus is available, it would not load tomorrow's schedule. Instead, all the timers are showing zero.~~

~~I would say this is just an enhancement. I personally think if all the timers are showing zero, reloading the page will solve this problem and I don't think this is a big deal.~~

~~We can either **merge this branch without solving this issue** or **merge after this issue is solved.**~~

**This content moved to issue** #7

**Comment by Taewan-P** [comment]
This code has bugs. When bus is not available for today, it would not show up the tomorrow's first bus departure time until it is past midnight.

**Pull request merged**
