### PR TITLE
For naver search result

### PR DESCRIPTION
**Pull request by mjkya**

### CODE REVIEW

**Review by Taewan-P — CHANGES_REQUESTED** [review]
Just uploading this file would not let Naver Webmaster to find this file. Instead, the site would return 404 ERROR.

I personally recommend adding the meta tag in our index.html for verification.
image

We also need to think about which naver account should we link with our service.

**Comment by mjkya** [comment]
either way would work, the site recommended adding a separate file but if other members think adding the HTML meta tag is better, I'll change

스크린샷 2020-10-22 오후 4 56 54

**Comment by Taewan-P** [comment]
Just uploading the html file to the directory **would not work.**
You need to specify the routes for the vue application to find the html page.
For example, try to locate our robots.txt in our website. It is already uploaded in the main directory, but if you actually go and check /robots.txt in the webpage, you will not see the page or will show 404. This is because we did not specifically set the routes for robots.txt.

**Comment by Taewan-P** [comment]
Webmaster verification finished. Closing this issue.

**Pull request closed without merging**
